server:
  port: 1112
  ssl:
    enabled: true
    key-store: classpath:static/server.keystore.p12
    key-store-password: DashaYana
    key-store-type: PKCS12
    key-alias: main-server

trust:
  store:
    url: classpath:static/server.keystore.p12
    password: DashaYana